swagger: '2.0'
info:
  version: '1.0'
  title: "SE2 group project - return to_sleep"
  description: Api for a exam and task system.
  license:
    name: MIT
    url: https://app-progettose2-return-tosleep.herokuapp.com/
host: polls.apiblueprint.org
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /user:
    x-summary: User Entity
    post:
      description: Crea un nuovo utente
      summary: Crea un nuovo utente
      responses:
        201:
          description: 'successful operation'
  /user/{username}:  
    put:
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      parameters:
      - name: "username"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
    delete:
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
  /user/login:
    get:
      summary: "Logs user into the system"
      description: ""
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid username/password supplied"
  /user/logout:
    get:
      summary: "Logs out current logged in user session"
      description: ""
      responses:
        200:
          description: "successful operation"
  /task:
    post:
      description: Consente di creare una nuova task
      summary: Crea una nuova task
      responses:
        201:
          description: 'successful operation'
    put:
      description: Consente di modificare una task esistente
      summary: Modifica una task
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Task not found'
        405:
          description: 'Validation exception'  
  /task/{taskid}:
    get:
      description: Ritorna una task
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to get"
        required: true
        type: "string"
      summary: Trova una task tramite id
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Task not found'
    delete:
      description: Elimina una task
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to be deleted"
        required: true
        type: "string"
      summary: Elimina una task
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Task not found'
  /task/{taskid}/answer:
    post:
      description: L'utente carica la propria risposta alla task
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to get answer"
        required: true
        type: "string"
      summary: Carica la risposta della task
      responses:
        200:
          description: 'Successful operation' 
  /task/findByTags:
    get:
      description: Ricerca le task in base ai tag (attributi). Serve per creare degli esami partendo da un pool di tasks.
      summary: Ricerca le task in base ai tag (attributi).
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid tag value'
  /task/{taskid}/evaluate:
    post:
      description: Consente di caricare la valutazione della task (voto + commento)
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to post"
        required: true
        type: "string"
      summary: Carica la valutazione della task
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid value'
        404:
          description: 'Task not found'
  
  /exam:
    post:
      description: Consente di creare un nuovo esame
      summary: Crea un un nuovo esame
      responses:
        201:
          description: 'successful operation'
    put:
      description: Consente di modificare un esame esistente
      summary: Modifica un esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
        405:
          description: 'Validation exception'
  /exam/{examid}:
    delete:
      description: Elimina un esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to delete"
        required: true
        type: "string"
      summary: Elimina un esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
  /exam/createWithList:
    post:
      description: Crea un esame con una data lista di task
      summary: Crea un esame con una data lista di task
      responses:
        200: 
          description: 'succesful operation'
          
          
  /group/createWithUserIdList:
    post:
      description: Consente di creare un nuovo gruppo data una lista di utenti 
      summary: Crea un un nuovo gruppo
      responses:
        201:
          description: 'successful operation'