swagger: '2.0'
info:
  version: '1.0'
  title: "SE2 group project - return to_sleep"
  description: Api for a exam and task system.
  license:
    name: MIT
    url: https://app-progettose2-return-tosleep.herokuapp.com/
host: polls.apiblueprint.org
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    post:
      description: Crea un nuovo utente
      summary: Crea un nuovo utente
      responses:
        201:
          description: 'successful operation'
    get:
      description: "Ritorna l'elenco di tutti gli utenti"
      summary: "Trova tutti gli utenti"
      responses:
        200:
          description: "Successful operation"
  /users/{username}:  
    put:
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      parameters:
      - name: "username"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
    delete:
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
  /users/login:
    get:
      summary: "Logs user into the system"
      description: ""
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid username/password supplied"
  /users/logout:
    get:
      summary: "Logs out current logged in user session"
      description: ""
      responses:
        200:
          description: "successful operation"
          
  /tasks:
    post:
      description: Consente di creare una nuova task
      summary: Crea una nuova task
      responses:
        201:
          description: 'successful operation'
    get:
      description: "Ritorna l'elenco di tutte le task"
      summary: "Trova tutte le task"
      responses:
        200:
          description: "Successful operation"
  /tasks/{taskid}:
    get:
      description: Ritorna una task
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to get"
        required: true
        type: "string"
      summary: Trova una task tramite id
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Task not found'
    put:
      description: Consente di modificare una task esistente
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to be updated"
        required: true
        type: "string"
      summary: Modifica una task
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Task not found'
        405:
          description: 'Validation exception'
    delete:
      description: Elimina una task
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to be deleted"
        required: true
        type: "string"
      summary: Elimina una task
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Task not found'
  /tasks/{taskid}/answer:
    post:
      description: L'utente carica la propria risposta alla task
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to get answer"
        required: true
        type: "string"
      summary: Carica la risposta della task
      responses:
        200:
          description: 'Successful operation' 
  /tasks/findByTags:
    get:
      description: Ricerca le task in base ai tag (attributi). Serve per creare degli esami partendo da un pool di tasks.
      summary: Ricerca le task in base ai tag (attributi).
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid tag value'
  /tasks/{taskid}/evaluate:
    post:
      description: Consente di caricare la valutazione della task (voto + commento)
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to post"
        required: true
        type: "string"
      summary: Carica la valutazione della task
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid value'
        404:
          description: 'Task not found'
  
  /exams:
    post:
      description: Consente di creare un nuovo esame
      summary: Crea un un nuovo esame
      responses:
        201:
          description: 'successful operation'
    get:
      description: "Ritorna l'elenco di tutti gli esami"
      summary: "Trova tutti gli esami"
      responses:
        200:
          description: "Successful operation"
  /exams/{examid}:
    get:
      description: Ritorna un esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to get"
        required: true
        type: "string"
      summary: Trova un esame tramite id
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
    put:
      description: Consente di modificare un esame esistente
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to be updated"
        required: true
        type: "string"
      summary: Modifica un esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
        405:
          description: 'Validation exception'
    delete:
      description: Elimina un esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to delete"
        required: true
        type: "string"
      summary: Elimina un esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
  /exams/insertTaskWithTaskList:
    post:
      description: Crea un esame con una data lista di task
      summary: Crea un esame con una data lista di task
      responses:
        200: 
          description: 'succesful operation'
          
  /groups:
    post:
      description: Consente di creare un nuovo gruppo
      summary: Crea un un nuovo gruppo
      responses:
        201:
          description: 'Successful operation'
    get:
      description: "Ritorna l'elenco di tutti i gruppi"
      summary: "Trova tutti i gruppi"
      responses:
        200:
          description: "Successful operation"
  /groups/{groupid}:
    get:
      description: Ritorna un gruppo
      parameters:
      - name: "groupid"
        in: "path"
        description: "The groupid that needs to get"
        required: true
        type: "string"
      summary: Trova un gruppo tramite id
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Group not found'
    put:
      description: Consente di modificare un gruppo esistente
      parameters:
      - name: "groupid"
        in: "path"
        description: "The groupid that needs to be updated"
        required: true
        type: "string"
      summary: Modifica un gruppo
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Group not found'
        405:
          description: 'Validation exception'
    delete:
      description: Elimina un esame
      parameters:
      - name: "groupid"
        in: "path"
        description: "The groupid that needs to delete"
        required: true
        type: "string"
      summary: Elimina un gruppo
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Group not found'
  /groups/createWithUserIdList:
    post:
      description: Consente di creare un nuovo gruppo data una lista di utenti 
      summary: Crea un un nuovo gruppo
      responses:
        201:
          description: 'successful operation'