swagger: '2.0'
info:
  version: '1.0'
  title: "SE2 group project - return to_sleep"
  description: Api for a exam and task system.
  license:
    name: MIT
    url: https://app-progettose2-return-tosleep.herokuapp.com/
host: polls.apiblueprint.org
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    post:
      description: Crea un nuovo utente
      summary: Crea un nuovo utente
      responses:
        201:
          description: 'successful operation'
    get:
      description: "Ritorna l'elenco di tutti gli utenti"
      summary: "Trova tutti gli utenti"
      responses:
        200:
          description: "Successful operation"
  /users/{username}:  
    put:
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      parameters:
      - name: "username"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
    delete:
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
  /users/{username}/exams:  
    get:
      summary: "Recupera esami per un utente"
      description: "This can only be done by the logged in user."
      parameters:
      - name: "username"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
  /users/login:
    get:
      summary: "Logs user into the system"
      description: ""
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid username/password supplied"
  /users/logout:
    get:
      summary: "Logs out current logged in user session"
      description: ""
      responses:
        200:
          description: "successful operation"
          
  /tasks:
    post:
      description: Consente di creare una nuova task
      summary: Crea una nuova task
      responses:
        201:
          description: 'successful operation'
    get:
      description: Ritorna l'elenco di tutte le task
      summary: Trova tutte le tasks
      responses:
        200:
          description: "Successful operation"
  /tasks/{taskid}:
    get:
      description: Ritorna una task
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to get"
        required: true
        type: "string"
      summary: Trova una task tramite id
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Task not found'
    put:
      description: Consente di modificare una task esistente
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to be updated"
        required: true
        type: "string"
      summary: Modifica una task
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Task not found'
        405:
          description: 'Validation exception'
    delete:
      description: Elimina una task
      parameters:
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to be deleted"
        required: true
        type: "string"
      summary: Elimina una task
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Task not found'
  
  /exams:
    post:
      description: Consente di creare un nuovo esame
      summary: Crea un un nuovo esame
      responses:
        201:
          description: 'successful operation'
    get:
      description: "Ritorna l'elenco di tutti gli esami"
      summary: "Trova tutti gli esami"
      responses:
        200:
          description: "Successful operation"
  /exams/{examid}:
    get:
      description: Ritorna un esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to get"
        required: true
        type: "string"
      summary: Trova un esame tramite id
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
    put:
      description: Consente di modificare un esame esistente
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to be updated"
        required: true
        type: "string"
      summary: Modifica un esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
        405:
          description: 'Validation exception'
    delete:
      description: Elimina un esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to delete"
        required: true
        type: "string"
      summary: Elimina un esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
  /exams/{examid}/tasks:
    post:
      description: Inserire tasks in un esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to get"
        required: true
        type: "string"
      summary: Inserisce task in un esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
    get:
      description: Ritorna le tasks di un esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to get"
        required: true
        type: "string"
      summary: Ritorna tutte le task inserite in un esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
  /exams/{examid}/tasks/{taskid}:
    put:
      description: Svolgere una task in un esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to get"
        required: true
        type: "string"
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to get"
        required: true
        type: "string"
      summary: Permette di svolgere una specifica task in uno specifico esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
    get:
      description: Ritorna una task di un esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to get"
        required: true
        type: "string"
      - name: "taskid"
        in: "path"
        description: "The taskid that needs to get"
        required: true
        type: "string"
      summary: Ritorna una specifica task in uno specifico esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
  /exams/{examid}/groups:
    post:
      description: Assegna un esame a un gruppo
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to get"
        required: true
        type: "string"
      summary: Permette di assegnare un esame a uno o più gruppi
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
    get:
      description: Ritorna i gruppi a cui è assegnato l'esame
      parameters:
      - name: "examid"
        in: "path"
        description: "The examid that needs to get"
        required: true
        type: "string"
      summary: Ritorna una lista dei gruppi ai quali è stato assegnato uno specifico esame
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Exam not found'
          
  /groups:
    post:
      description: Consente di creare un nuovo gruppo
      summary: Crea un un nuovo gruppo
      responses:
        201:
          description: 'Successful operation'
    get:
      description: "Ritorna l'elenco di tutti i gruppi"
      summary: "Trova tutti i gruppi"
      responses:
        200:
          description: "Successful operation"
  /groups/{groupid}:
    get:
      description: Ritorna un gruppo
      parameters:
      - name: "groupid"
        in: "path"
        description: "The groupid that needs to get"
        required: true
        type: "string"
      summary: Trova un gruppo tramite id
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Group not found'
    put:
      description: Consente di modificare un gruppo esistente
      parameters:
      - name: "groupid"
        in: "path"
        description: "The groupid that needs to be updated"
        required: true
        type: "string"
      summary: Modifica un gruppo
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Group not found'
        405:
          description: 'Validation exception'
    delete:
      description: Elimina un esame
      parameters:
      - name: "groupid"
        in: "path"
        description: "The groupid that needs to delete"
        required: true
        type: "string"
      summary: Elimina un gruppo
      responses:
        400:
          description: 'Invalid ID supplied'
        404:
          description: 'Group not found'

definitions:
  Task:
    title: Task
    type: object
    properties:
      taskid:
        type: integer
        format: int32
      tipologia:
        type: string
        enum: [Aperta, Radiobox, Checkbox]
        oneOf:
          - $ref: '#/definitions/Aperta'
          - $ref: '#/definitions/Radiobox'
          - $ref: '#/definitions/Checkbox'
    required:
      - taskid

  Radiobox:
    title: Radiobox
    type: object
    properties:
      domanda: 
        type: string
      options:
        type: array
        items: 
          $ref: '#/definitions/Choice'
      risposta: 
        type: string
    required:
      - domanda
      - choices

  Checkbox:
    title: Checkbox
    type: object
    properties:
      domanda: 
        type: string
      options: 
        type: array
        items:
          $ref: '#/definitions/Choice'
      risposta: 
        type: array
        items:
          type: string
    required:
      - domanda
      - choices

  Choice:
    title: Choice
    type: object
    properties:
      choice: 
        type: string
      selection: 
        type: boolean
    required:
     - choice

  Aperta:
    title: Aperta
    type: object
    properties:
      domanda: 
        type: string
      riposta: 
        type: string
    required: 
      - domanda

  User:
    title: User
    type: object
    properties:
      username: 
        type: string
      nome: 
        type: string
      cognome: 
        type: string
      email: 
        type: string
      matricola:
        type: integer
        format: int32
    required:
      - username
      - matricola

  Group:
    title: Group
    type: object
    properties:
      groupid: 
        type: integer
        format: int32
      componenti: 
        type: array
        items:
          $ref: '#/definitions/User'
    required:
      - groupid

  Exam:
    title: Exam
    type: object
    properties:
      examid:
        type: integer
        format: int32
      creator:
        type: object
        $ref: '#/definitions/User'
      tasks: 
        type: array
        items:
          $ref: '#/definitions/Task'
      groups: 
        type: array
        items:
          $ref: '#/definitions/Group'