swagger: '2.0'
info:
  version: '1.0'
  title: "SE2 group project - return to_sleep"
  description: Api for a exam and task system.
  license:
    name: 
    url: 
host:  
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /user:
    x-summary: User Entity
    post:
      description: Crea un nuovo utente
      summary: Crea un nuovo utente
      responses:
        201:
          description: 'successful operation'
  /user/{username}:  
    put:
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      parameters:
      - name: "username"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
    delete:
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
  /user/login:
    get:
      summary: "Logs user into the system"
      description: ""
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid username/password supplied"
  /user/logout:
    get:
      summary: "Logs out current logged in user session"
      description: ""
      responses:
        default:
          description: "successful operation"